name: Generate ZIP file

on:
  workflow_dispatch:
  workflow_call:

jobs:
    generate-zip-file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Cache node_modules
              id: cache-node-modules
              uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
              env:
                  cache-name: cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

            - name: Setup node version and npm cache
              uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Setup PHP
              uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
              with:
                php-version: '7.4'
                tools: composer:v2

            - name: Install Node dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm ci --no-optional

            - name: Generate ZIP file
              run: npm run build && rm -rf ./woocommerce-gateway-payfast && unzip woocommerce-gateway-payfast.zip -d ./woocommerce-gateway-payfast

            - name: Use the Upload Artifact GitHub Action
              uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
              with:
                  name: woocommerce-gateway-payfast
                  path: woocommerce-gateway-payfast/
