name: PHP Coding Standards

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup proper PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.php

      - name: Install dependencies
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: composer install

      - name: Run PHP_CodeSniffer
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          HEAD_REF=$(git rev-parse HEAD)
          git checkout $HEAD_REF
          ./vendor/bin/phpcs-changed -s --git --git-base origin/${{ github.base_ref }} ${{ steps.changed-files.outputs.all_changed_files }}
